[package]
name = "LINUX_DRIVER_IN_RUST"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]

[[bin]]
name = "hello_worl"
path = "app/hello.rs"

[[test]]
name = "test_hello_world"
path = "tests/test_hello.rs"
harness = false
