# Taskfile.yml
version: '3'

tasks:
  build:
    cmds:
      - rustc hello.rs
    silent: false

  run:
    cmds:
      - ./hello
    silent: false

  clean:
    cmds:
      - rm hello
    silent: true

